version: "3.9"
services:
  collector:
    build: ./Collector/
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.11.3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672" # Only for developpement purposes (can be removed in production)
  frontend:
    build:
      context: ./frontend/
    depends_on:
      - backend
    ports:
      - "3000:3000"
  backend:
    build: ./backend/
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    ports:
        - "4000:4000"
  processingunit:
    build: ./processing-storage-unit/
    depends_on:
      - rabbitmq