version: "3.9"
services:
  collector:
    build: ./Collector/
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.11.3-management-alpine
    ports:
      - "15672:15672"
  frontend:
    build: ./frontend/
    depends_on:
      - backend
    ports:
      - "3000:3000"
  backend:
    build: ./backend/
    depends_on:
      - rabbitmq